### ISSUE TITLE
Options are cropped.

### ISSUE THREAD

**Issue by mzso** [Ede123/greasy-scripts#5]
Hello!
Some options are cropped in the settings page, which makes it hard to tell what they stand for:
![gs-opt](https://cloud.githubusercontent.com/assets/4479090/8512370/96649ed6-233f-11e5-85fd-0b7202a90e5d.PNG)

**Comment by Ede123** [comment]
Since I'm not seeing it on my system:
- Which OS do you use?
- Have you changed the default font size (either in the OS or in Firefox)?

**Comment by mzso** [comment]
Well they changed the design of about:addons starting from ff40. (This is nightly)
This is on windows and it's just plain zoomed which shouldn't affect this. (Also changed fonts, but without that the top one is still cropped)
Anyway I thought that a wider dropdown box with more padding wouldn't hurt. It would be less likely to result in issues like this with further design changes.

**Comment by Ede123** [comment]
Turns out there is no universal fix for this:
- Firefox 39 and earlier crops the menupopups if no fixed width is specified
- Firefox 40 and later might crop the menupopups if a fixed width is specified

I went with removing the fixed width anyway since it will at least fix the issues for future versions of Firefox (the suboptimal behavior of previous Firefox versions could actually be considered a bug in Firefox itself)
