### ISSUE TITLE
Please support userscripts-mirror.org

### ISSUE THREAD

**Issue by alexolog** [Ede123/greasy-scripts#8]
userscripts-mirror.org has a large number of scripts that are not hosted on GreasyFork.  Please support that site as well, preferably with filtering out duplications.

Code to do that can be found here: https://addons.mozilla.org/en-US/firefox/addon/greasefire2/

Thank you!

**Comment by Ede123** [comment]
I'm hesitant to put any work into this for a whole lot of reasons:
- First of all: We already have an extension for this! [Greasefire2](https://github.com/B0nk3rZ/greasefire2) already does the job. There might be some compatibility issues, if desired and if @B0nk3rZ is available we might figure those out so the both extensions can be used side-by-side.
- Secondly userscripts-mirror.org (at least as far as I'm aware) does not have an API to gather script information per site. Greasfire 2 therefore uses a huge DB that contains information on all scripts available. This is exactly the method I do _not_ want to use since it adds a huge amount of overhead (you might notice Greasfire2 slows down every page load since it has to dig through the whole database every time). This might be optimized but would need _a lot_ of work.
- Lastly and most importantly: Userscripts.org is dead (and so is userscripts-mirror.org - it's only a non-editable copy of the original site). While some scripts there might still work, sooner or later they will cease to do so. Every script that is actively developed is likely to have already been migrated to one of the alternative userscripts sites. There's not much point in adding support for a dead project.

**Comment by alexolog** [comment]
without local caching we only have a choice between querying on every page, which slows down operation and increases bandwidth use, or manual checking.

Greasefire's method of keeping a local repository with periodic updates seems like a good compromise.

**Comment by yfdyh000** [comment]
I think the "Only when opening the menu" is a good option to do this and other cases.
If it has a "Loading ..." text, which will be better.
